#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
*/

require __DIR__ . '/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
*/

$app = require_once __DIR__ . '/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan App
|--------------------------------------------------------------------------
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$input = new Symfony\Component\Console\Input\ArgvInput;

$output = new Symfony\Component\Console\Output\ConsoleOutput;

$status = $kernel->handle($input, $output);

$kernel->terminate($input, $status);

/*
|--------------------------------------------------------------------------
| Shutdown The Artisan App
|--------------------------------------------------------------------------
*/

exit($status);
